# Generated by Django 5.2.4 on 2025-07-21 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0004_remove_order_business_user_remove_order_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sales_app.offer'),
        ),
    ]
