# Generated by Django 5.2.4 on 2025-07-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0003_userprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='avatars/'),
        ),
    ]
